# Generated by Django 4.2.1 on 2023-06-19 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_testimonials_delete_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonials',
            name='paragraph',
            field=models.TextField(blank=True),
        ),
    ]
