# Generated by Django 4.2.1 on 2023-06-19 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0007_testimonials_created_at_alter_testimonials_paragraph'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonials',
            name='company',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
